vich_uploader:
    db_driver: orm  # Cette ligne est obligatoire

    mappings:
        car_images:
            uri_prefix: /uploads/cars
            upload_destination: '%kernel.project_dir%/public/uploads/cars'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            directory_namer: null